feat(hooks): add test post-receive hook

diff --git a/hooks/post-receive b/hooks/post-receive
--- a/hooks/post-receive
+++ b/hooks/post-receive
@@ -1,30 +1,48 @@
-#!/bin/sh
+#!/bin/bash
 
-# Variables needed for the build
-# APP_NAME="my-app"
-# BUILD_DIR="/path/to/build/directory"
-# REGISTRY_URL="your-private-registry-url"
-# REGISTRY_USERNAME="your-registry-username"
-# REGISTRY_PASSWORD="your-registry-password"
+echo $IMAGE_NAME
 
-# Change to the build directory
-cd "$BUILD_DIR"
+if [ -z "$PWD" ]; then
+  echo "PWD is not set"
+  exit 1
+fi
 
-# Build the image using buildpack
-echo "Building image..."
-pack build "$APP_NAME" --builder heroku/buildpacks
+project_name=$(basename "$PWD")
 
-# An example using docker :  Log in to the private registry
-echo "Logging in to the private registry..."
-echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USERNAME" --password-stdin "$REGISTRY_URL"
+branch="main"
 
-# Tag the image with the registry URL
-TAG="$REGISTRY_URL/$APP_NAME"
-docker tag "$APP_NAME" "$TAG"
+ref="refs/heads/$BRANCH"
 
-# Push the image to the private registry
-echo "Pushing image to the private registry..."
-docker push "$TAG"
+timestamp=$(date +%s.%N)
 
-# Clean up - remove the locally built image
-docker image rm "$APP_NAME"
+target="/tmp/deploy-dir-$project_name-$timestamp"
+
+mkdir -p "$target"
+
+git --work-tree="$target" --git-dir=. checkout -f "$branch"
+
+# if there's a dockerfile, just use docker build
+if [ -f "$target/Dockerfile" ]; then
+  docker build -t "$IMAGE_NAME:latest" "$target"
+
+  rm -rf "$target"
+
+  if $? -ne 0; then
+    echo "docker build failed"
+    exit 1
+  fi
+
+  echo "docker build succeeded, you can now run : paastech deploy"
+  exit 0
+fi
+
+pack build "$IMAGE_NAME:latest" --path "$target" --builder heroku/buildpacks:20
+
+rm -rf "$target"
+
+if $? -ne 0; then
+  echo "pack build failed"
+  exit 1
+fi
+
+echo "pack build succeeded, you can now run : paastech deploy"
